version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - dupl
    - prealloc
    - nolintlint
    - revive
    - whitespace

  settings:
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    revive:
      rules:
        - name: var-naming
        - name: exported
